// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SqlTools
{
    internal sealed partial class Vsix
    {
        public const string Id = "SqlTools.e8fe6622-1282-4bcc-874e-ef26d37daea3";
        public const string Name = "Sql Tools";
        public const string Description = @"SQL syntax highlighting (keywords, operators, functions and variables) to string literals";
        public const string Language = "en-US";
        public const string Version = "1.4";
        public const string Author = "Mojtaba Kaviani";
        public const string Tags = "SQL, syntax highlighting, string literals";
    }
}
